#!/bin/sh

sudo apt install gnupg curl wget git -y && \
sudo curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor && \
sudo echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list && \
sudo apt update -y && \
sudo apt install ./requirments-mongodb/libssl1.1_1.1.1f-1ubuntu2_amd64.deb -y && \
sudo apt install mongodb-org -y && \
sudo systemctl start mongod && \
sudo systemctl enable mongod && \
sudo wget https://downloads.mongodb.com/compass/mongodb-compass_1.28.4_amd64.deb && \
sudo apt install ./requirments-mongodb/gconf2-common_3.2.6-8_all.deb -y && \
sudo apt install ./requirments-mongodb/libgconf-2-4_3.2.6-8_amd64.deb -y && \
sudo apt install ./mongodb-compass_1.28.4_amd64.deb -y && \
sudo rm -r ./mongodb-compass_1.28.4_amd64.deb && \
sudo clear && \
sudo echo "mongoDB and mongoDB Compass Successfuly Installed"
